# workflow의 이름
name: backend-deploy-test

# PR 요청에 대해
on:
  pull_request:
    branches:
      - main
    # pr이 생성 되었을 때, 담당 유저가 등록되었을 때, PR에 코드가 머지되었을 때, 라벨이 달렸을 때 동작
    types: [closed]

# 실행 해야할 job
jobs:
  # Job의 이름, 자유롭게 짓습니다.
  ###### 본문 내용과 관련 없는 Job, 빌드 테스트
  build:
    # ubuntu 환경에서 실행 (환경은 github이 제공)
    runs-on: self-hosted
    # 각 단계
    steps:
      # 소스코드 체크아웃
      # 빌드
      - name: echo
        run: echo "run complete" > test.txt
