# workflow의 이름
name: label-test

# PR 요청에 대해
on:
  pull_request:
    branches:
      - main
    # pr이 생성 되었을 때, 담당 유저가 등록되었을 때, PR에 코드가 머지되었을 때, 라벨이 달렸을 때 동작
    types: [ opened, synchronize, reopened ]
  workflow_dispatch:

# 실행 해야할 job
jobs:
  # Job의 이름, 자유롭게 짓습니다.
  ###### 본문 내용과 관련 없는 Job, 빌드 테스트
  if-label-BE:
    # label [BE] 일때만 동작
    if: contains(github.event.pull_request.labels.*.id, 5686155001)
    # ubuntu 환경에서 실행 (환경은 github이 제공)
    runs-on: ubuntu-latest
    # 각 단계
    steps:
      # 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3
      # 빌드
      - name: Build Test
        run: echo "labeled BE"

  always:
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.id, 5686155001)
    # 각 단계
    steps:
      # 소스코드 체크아웃
      - name: Checkout source code
        uses: actions/checkout@v3
      # 빌드
      - name: label Test
        run: echo "FE"
